---
version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_USER: ayeni
            MYSQL_PASSWORD: ayeni
            MYSQL_ROOT_PASSWORD: ayeni
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistentvol:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: ayeni
            MYSQL_PASSWORD: ayeni
            MYSQL_ROOT_PASSWORD: ayeni
volumes:
    persistentvol:

